### ISSUE TITLE
如何考虑并发的安全性

### ISSUE THREAD

**Issue by linml** [toniz/gudp#1]
我看你这边的处理是直接接受客户端请求过来的数据，并执行对应的操作，那考虑并发的安全性，这一点如何处理

**Comment by linml** [comment]
多客户端模式（不同系统）

**Comment by toniz** [comment]
这个工程仅提供一个统一数据库操作的思路和DEMO。如果要用于真实环境，还需要根据自己项目的实际需求去增加以及修改代码。

**Comment by toniz** [comment]
如果要去考虑安全性，增加登陆以及session之类的校验的代码，把读取之类比较简单的通过SQL直接开放到APP，把写之类危险的通过BO层来访问该服务。目前GUDP通过参数替换和单语句执行，是能有效防御SQL注入的。
